Papermc arclight
kmcsr/server-installer pull request #1
Opened 2024-03-07 07:47 UTC by Fellsoul

把papermc和arclight的下载器做好了，在readme里改了日志。本地都调试过了，papermc支持所有有的版本，arclight多加了一个判断并且告诉用户什么版本已经expired不能再选了（虽然强硬要选也会被驳回吧

2024-03-07 22:13 UTC, zyxkad approved these changes

2024-03-07 22:31 UTC, zyxkad requested changes

2024-03-07 22:31 UTC, zyxkad commented on arclight_installer.go
> +DownloadPart:
Label 用全大写字母+下划线，另外，能不用goto就别用

2024-03-07 22:31 UTC, zyxkad commented on arclight_installer.go
> +	currentDir, err := os.Getwd()
`Getwd` 和 `.` 一个意思，这里没有必要再获取一遍

2024-03-07 22:31 UTC, zyxkad commented on arclight_installer.go
> +	serverDirectory := filepath.Join(currentDir, "server-"+ExactDownloadName[0:len(ExactDownloadName)-4])
不要出现 `len(ExactDownloadName)-4` 这样需要联系方法外上下文的迷之操作

2024-03-07 22:31 UTC, zyxkad commented on cli/usage.go
> -
usage 太长，所以单放一个文件

2024-03-07 22:31 UTC, zyxkad commented on httpclient.go
> +	resp, err := http.Head(url)
这个用不到的操作是做甚的

2024-03-07 22:31 UTC, zyxkad commented on httpclient.go
> +	flags := os.O_CREATE | os.O_WRONLY
flags 不用单列出一个变量，因为下面用不到，也不会被修改

2024-03-07 22:31 UTC, zyxkad commented on httpclient.go
> +	f, err := os.OpenFile(filename, flags, 0666)
`0666`不是安全的权限，改成`0644`

2024-03-07 22:31 UTC, zyxkad commented on httpclient.go
> +	buf := make([]byte, 16*1024)
如果是现make buffer就别make了，直接用`io.Copy`

2024-03-07 22:31 UTC, zyxkad commented on papermc_installer.go
> +	link := "https://api.papermc.io/v2/projects/paper"
常量用 const, 另外你上面定义了 paperURL 这里为什么还要 hardcode

2024-03-07 22:31 UTC, zyxkad commented on papermc_installer.go
> +	installed = buildJar + "\n"
installer 不换行啊，这是通知可能存在的父程序文件下载到哪里去了

2024-03-07 22:46 UTC, zyxkad requested changes

2024-03-07 22:46 UTC, zyxkad commented on arclight_installer.go
> +	for i := 0; i < len(releases); i += 1 {
`i += 1` 就是 `i++`

2024-03-07 22:46 UTC, zyxkad commented on arclight_installer.go
> +		if year < 2024 || (year == 2024 && month < 2) {
`year < 2024` 是个什么操作????

2024-03-07 22:46 UTC, zyxkad commented on README.MD
> +# Install papermc 1.14.4 server into {PATH}/server-1.14.4-{BUILDNUM}/{PAPERMC-INSTALLED-NAME}.jar
格式错了，应该下载到提供的 `name` 参数那里去

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +			if data[allVersions[i]].IsExpired == true {
为什么我还是能遇到 == true 这种操作 😓 

```suggestion
			if data[allVersions[i]].IsExpired {
```

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +func (r *ArclightInstaller) GetOnlyVersions(data map[string]ArclightRelease) (versions []string) {
`GetOnlyVersions` 是干嘛的，如果是辅助函数那就不要放到 Installer 的方法里

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +	for k := range data {
```suggestion
	for k, _ := range data {
```

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +		for i := 0; i < len(allVersions); i += 1 {
```suggestion
		for _, version := range allVersions {
```

或者直接

```suggestion
		for version, _ := range data {
```

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +	for i := 0; i < len(releases); i += 1 {
```suggestion
	for _, release := range releases {
```

2024-03-07 23:04 UTC, zyxkad commented on arclight_installer.go
> +	var releases []ArclightRelease
```suggestion
	var releases []*ArclightRelease
```

2024-03-07 23:07 UTC, zyxkad commented on arclight_installer.go
> +	if data[loader].IsExpired == true {
你不能假设loader存在于data里
```suggestion
	if version, ok := data[loader]; ok && version.IsExpired {
```

2024-03-07 23:07 UTC, zyxkad commented on arclight_installer.go
> +	data, err := r.GetInstallerVersions()
`data` 这个名字太笼统了，换成 `versions`

2024-03-11 15:08 UTC, Fellsoul commented on papermc_installer.go
> +	link := "https://api.papermc.io/v2/projects/paper"
我的错。我不明白“url”的因素。我认为其他文件中引用了它们

2024-03-11 15:10 UTC, Fellsoul commented on papermc_installer.go
> +	installed = buildJar + "\n"
正确的。我没有意识到变量用作地址，只考虑输出

2024-03-11 15:15 UTC, Fellsoul commented on arclight_installer.go
> +		if year < 2024 || (year == 2024 && month < 2) {
判断是否过期，因为在2024.2月以前的所有构建都失效了，而且想不到比这样判断更好的方法了，就直接这样硬编码了

2024-03-11 15:17 UTC, Fellsoul commented on README.MD
> +# Install papermc 1.14.4 server into {PATH}/server-1.14.4-{BUILDNUM}/{PAPERMC-INSTALLED-NAME}.jar
好的我run所有文件再调试一下，之前不是太清楚命令行操作

2024-03-11 15:19 UTC, Fellsoul commented on arclight_installer.go
> +			if data[allVersions[i]].IsExpired == true {
哦我明白了 false和nil有内存区别，c的判断逻辑是nil和false是否

2024-03-11 15:23 UTC, Fellsoul commented on arclight_installer.go
> +	if data[loader].IsExpired == true {
疏忽了

2024-03-11 15:23 UTC, Fellsoul commented on arclight_installer.go
> +	data, err := r.GetInstallerVersions()
好的

2024-03-29 20:49 UTC, zyxkad requested changes

2024-03-29 20:49 UTC, zyxkad commented on README.MD
> +# Install papermc 1.14.4 server into server/minecraft_server.jar
```suggestion
# Install papermc 1.14.4 server into minecraft_server.jar
```

2024-03-29 20:50 UTC, closed without merging